defmodule FizzBuzzTest do
  use ExUnit.Case
  doctest FizzBuzz

  test "play" do
    result = [
      1,
      2,
      "Fizz",
      4,
      "Buzz",
      "Fizz",
      7,
      8,
      "Fizz",
      "Buzz",
      11,
      "Fizz",
      13,
      14,
      "Fizz Buzz",
      16,
      17,
      "Fizz",
      19,
      "Buzz",
      "Fizz",
      22,
      23,
      "Fizz",
      "Buzz",
      26,
      "Fizz",
      28,
      29,
      "Fizz Buzz",
      31,
      32,
      "Fizz",
      34,
      "Buzz",
      "Fizz",
      37,
      38,
      "Fizz",
      "Buzz",
      41,
      "Fizz",
      43,
      44,
      "Fizz Buzz",
      46,
      47,
      "Fizz",
      49,
      "Buzz"
    ]

    assert result == FizzBuzz.play_naive(50)
    assert result == FizzBuzz.play_func(50)

    assert FizzBuzz.play_polish(50) ==
             [
               "Zazz",
               "Zazz",
               "Fizz Zazz",
               "Zazz",
               "Buzz Zazz",
               "Fizz Zazz",
               "Zazz",
               "Zazz",
               "Fizz Zazz",
               "Buzz",
               11,
               "Fizz",
               13,
               14,
               "Fizz Buzz",
               16,
               17,
               "Fizz",
               19,
               "Buzz",
               "Fizz",
               22,
               23,
               "Fizz",
               "Buzz",
               26,
               "Fizz",
               28,
               29,
               "Fizz Buzz",
               31,
               32,
               "Fizz",
               34,
               "Buzz",
               "Fizz",
               37,
               38,
               "Fizz",
               "Buzz",
               41,
               "Fizz",
               43,
               44,
               "Fizz Buzz",
               46,
               47,
               "Fizz",
               49,
               "Buzz"
             ]
  end
end
